### Importação de Dados

In [1]:
import pandas as pd

### Coletando os dados - Empréstimos

In [2]:
arquivos = [
    'emprestimos-20101.csv', 'emprestimos-20102.csv',
    'emprestimos-20111.csv', 'emprestimos-20112.csv',
    'emprestimos-20121.csv', 'emprestimos-20122.csv', 
    'emprestimos-20131.csv', 'emprestimos-20132.csv', 
    'emprestimos-20141.csv', 'emprestimos-20142.csv',
    'emprestimos-20151.csv', 'emprestimos-20152.csv',
    'emprestimos-20161.csv', 'emprestimos-20162.csv',
    'emprestimos-20171.csv', 'emprestimos-20172.csv',
    'emprestimos-20181.csv', 'emprestimos-20182.csv',
    'emprestimos-20191.csv', 'emprestimos-20192.csv',
    'emprestimos-20201.csv'
]

In [3]:
base_url = 'https://raw.githubusercontent.com/FranciscoFoz/7_Days_of_Code_Alura-Python-Pandas/main/Dia_1-Importando_dados/Datasets/dados_emprestimos/'

In [4]:
emprestimos = []

In [5]:
for arquivo in arquivos:
    url_completa = f"{base_url}{arquivo}"
    df_temp = pd.read_csv(url_completa)
    emprestimos.append(df_temp)
    print (f'Arquivo {arquivo} importado com sucesso!')

Arquivo emprestimos-20101.csv importado com sucesso!
Arquivo emprestimos-20102.csv importado com sucesso!
Arquivo emprestimos-20111.csv importado com sucesso!
Arquivo emprestimos-20112.csv importado com sucesso!
Arquivo emprestimos-20121.csv importado com sucesso!
Arquivo emprestimos-20122.csv importado com sucesso!
Arquivo emprestimos-20131.csv importado com sucesso!
Arquivo emprestimos-20132.csv importado com sucesso!
Arquivo emprestimos-20141.csv importado com sucesso!
Arquivo emprestimos-20142.csv importado com sucesso!
Arquivo emprestimos-20151.csv importado com sucesso!
Arquivo emprestimos-20152.csv importado com sucesso!
Arquivo emprestimos-20161.csv importado com sucesso!
Arquivo emprestimos-20162.csv importado com sucesso!
Arquivo emprestimos-20171.csv importado com sucesso!
Arquivo emprestimos-20172.csv importado com sucesso!
Arquivo emprestimos-20181.csv importado com sucesso!
Arquivo emprestimos-20182.csv importado com sucesso!
Arquivo emprestimos-20191.csv importado com sucesso!
Arquivo emprestimos-20192.csv importado com sucesso!
Arquivo emprestimos-20201.csv importado com sucesso!

In [6]:
emprestimos_total = pd.concat(emprestimos, ignore_index=True)

print (f"\nTotal de linhas: {len(emprestimos_total)}")
emprestimos_total.head()

Total de linhas: 2258018

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO

Coletando Dados - Exemplares do Acervo

In [7]:
url_acervo = 'https://github.com/FranciscoFoz/7_Days_of_Code_Alura-Python-Pandas/raw/refs/heads/main/Dia_1-Importando_dados/Datasets/dados_exemplares.parquet'

In [8]:
acervo = pd.read_parquet(url_acervo)
acervo.head()

,id_exemplar,codigo_barras,colecao,biblioteca,status_material,localizacao,registro_sistema
index,,,,,,,
0,5,L000003,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,694,1
1,4,L000002,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,688,1
2,3,L000001,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,638,1
3,7,L000114,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,616,5
5,10,L000041,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,657,15

### Concatenação dos Dataframes

In [9]:
emprestimos_biblioteca = pd.concat([emprestimos_total, acervo], ignore_index=True)

emprestimos_biblioteca.tail()

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
2804250,NaN,2021011150,NaN,NaN,NaN,NaN,NaN,1353472.0,Acervo Circulante,Biblioteca Setorial do Núcleo de Educação da I...,REGULAR,951.0,268231.0
2804251,NaN,2019013454,NaN,NaN,NaN,NaN,NaN,1353473.0,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,997.0,268233.0
2804252,NaN,2019012811,NaN,NaN,NaN,NaN,NaN,1353474.0,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,987.0,268234.0
2804253,NaN,2019013451,NaN,NaN,NaN,NaN,NaN,1353475.0,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,764.0,268235.0
2804254,NaN,2019012276,NaN,NaN,NaN,NaN,NaN,1353476.0,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,962.0,268236.0

### Removendo linhas duplicadas

In [10]:
emprestimos_biblioteca.duplicated().sum()

np.int64(37)

In [11]:
duplicadas = emprestimos_biblioteca[emprestimos_biblioteca.duplicated()]
duplicadas

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
4,709684.0,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
5,709685.0,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
6,709686.0,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
7,709687.0,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
19,709698.0,2009047725,2010/01/18 14:44:41.163000000,2010/01/04 09:21:19.099000000,2010/02/02 12:02:38.444000000,2.009047e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
20,709698.0,2009047725,2010/01/18 14:44:41.163000000,2010/01/04 09:21:19.099000000,2010/02/02 12:02:38.444000000,2.009047e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
28,709704.0,2006021442,2010/01/17 18:56:43.923000000,2010/01/04 09:58:46.522000000,2010/02/01 13:59:02.528000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
29,709705.0,2009032168,2010/01/17 18:56:43.909000000,2010/01/04 09:58:46.549000000,2010/01/20 13:14:34.464000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
30,709704.0,2006021442,2010/01/17 18:56:43.923000000,2010/01/04 09:58:46.522000000,2010/02/01 13:59:02.528000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
31,709705.0,2009032168,2010/01/17 18:56:43.909000000,2010/01/04 09:58:46.549000000,2010/01/20 13:14:34.464000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
32,709704.0,2006021442,2010/01/17 18:56:43.923000000,2010/01/04 09:58:46.522000000,2010/02/01 13:59:02.528000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
33,709705.0,2009032168,2010/01/17 18:56:43.909000000,2010/01/04 09:58:46.549000000,2010/01/20 13:14:34.464000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
34,709704.0,2006021442,2010/01/17 18:56:43.923000000,2010/01/04 09:58:46.522000000,2010/02/01 13:59:02.528000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
35,709705.0,2009032168,2010/01/17 18:56:43.909000000,2010/01/04 09:58:46.549000000,2010/01/20 13:14:34.464000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
36,709704.0,2006021442,2010/01/17 18:56:43.923000000,2010/01/04 09:58:46.522000000,2010/02/01 13:59:02.528000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
37,709705.0,2009032168,2010/01/17 18:56:43.909000000,2010/01/04 09:58:46.549000000,2010/01/20 13:14:34.464000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
38,709704.0,2006021442,2010/01/17 18:56:43.923000000,2010/01/04 09:58:46.522000000,2010/02/01 13:59:02.528000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
39,709705.0,2009032168,2010/01/17 18:56:43.909000000,2010/01/04 09:58:46.549000000,2010/01/20 13:14:34.464000000,2.008010e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1394906,2351375.0,L057436,2016/01/31 07:30:36.293000000,2016/01/02 08:38:40.009000000,2016/02/21 13:16:29.000000000,2.016101e+10,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1394907,2351376.0,H004983,2016/01/31 07:31:36.786000000,2016/01/02 08:46:42.991000000,2016/02/22 16:10:28.000000000,2.016101e+10,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1394908,2351377.0,H011333,2016/01/31 07:31:36.658000000,2016/01/02 08:46:43.400000000,2016/02/22 16:10:40.000000000,2.016101e+10,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1394924,2351385.0,2013114886,2016/01/16 07:41:19.590000000,2016/01/02 10:02:44.456000000,2016/01/30 07:52:10.000000000,2.015316e+09,ALUNO MÉDIO/TÉCNICO,NaN,NaN,NaN,NaN,NaN,NaN
1394925,2351386.0,2015005192,2016/01/16 07:41:19.537000000,2016/01/02 10:02:44.507000000,2016/01/30 07:52:07.000000000,2.015316e+09,ALUNO MÉDIO/TÉCNICO,NaN,NaN,NaN,NaN,NaN,NaN
1394926,2351387.0,2015004940,2016/01/16 07:41:19.473000000,2016/01/02 10:02:44.560000000,2016/01/30 07:52:00.000000000,2.015316e+09,ALUNO MÉDIO/TÉCNICO,NaN,NaN,NaN,NaN,NaN,NaN
1394927,2351388.0,2012029817,NaN,2016/01/02 10:08:27.599000000,2016/01/23 16:28:01.000000000,2.016101e+10,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1394928,2351389.0,2014077426,NaN,2016/01/02 10:08:27.658000000,2016/01/23 16:27:57.000000000,2.016101e+10,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1394929,2351390.0,2015007050,2016/01/31 23:03:17.389000000,2016/01/02 10:08:27.720000000,2016/03/16 16:26:37.000000000,2.016101e+10,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1394930,2351391.0,L195470,2016/01/17 16:03:38.760000000,2016/01/02 10:12:01.462000000,2016/01/27 16:37:55.000000000,2.014036e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1394931,2351392.0,2015008037,2016/01/17 16:03:38.705000000,2016/01/02 10:12:01.529000000,2016/01/27 16:37:59.000000000,2.014036e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1504567,2461092.0,2014007909,NaN,2016/06/14 11:13:44.817000000,2016/06/16 09:55:01.000000000,2.016089e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1504568,2461093.0,2014007908,NaN,2016/06/14 11:15:48.131000000,2016/06/23 10:06:35.000000000,2.016014e+10,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1504569,2461094.0,2014007910,NaN,2016/06/14 11:16:34.407000000,2016/06/22 08:04:20.000000000,2.016013e+10,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1504570,2461095.0,2014007744,NaN,2016/06/14 11:16:34.459000000,2016/06/22 08:04:39.000000000,2.016013e+10,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1504571,2461096.0,2016005538,NaN,2016/06/14 11:16:58.596000000,2016/07/04 16:07:41.000000000,2.016014e+10,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1504572,2461097.0,2014083427,NaN,2016/06/14 11:17:29.152000000,2016/06/16 09:17:19.000000000,2.016014e+10,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1504573,2461098.0,2014049460,NaN,2016/06/14 11:18:59.254000000,2016/06/26 13:44:13.000000000,2.017005e+10,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1504574,2461099.0,2012008348,2016/06/27 20:35:46.855000000,2016/06/14 11:20:33.254000000,2016/07/11 14:37:29.000000000,2.015022e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
emprestimos_biblioteca.drop_duplicates(inplace=True)

In [13]:
emprestimos_biblioteca.head()

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,709684.0,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
1,709685.0,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
2,709686.0,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
3,709687.0,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN
8,709688.0,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN

### Atribuir a coluna com nomeclatura da CDU

In [15]:
CDU_lista =[]

In [16]:
for CDU in emprestimos_biblioteca['localizacao']:
    if (CDU < 100):
        CDU_lista.append('Generalidades')
    elif (CDU < 200):
        CDU_lista.append('Filosofia e psicologia')
    elif (CDU < 300):
        CDU_lista.append('Religião')
    elif (CDU < 400):
        CDU_lista.append('Ciências sociais')
    elif (CDU < 500):
        CDU_lista.append('Classe vaga')
    elif (CDU < 600):
        CDU_lista.append('Matemática e ciências naturais')
    elif (CDU < 700):
        CDU_lista.append('Ciências aplicadas')
    elif (CDU < 800):
        CDU_lista.append('Belas artes')
    elif (CDU < 900):
        CDU_lista.append('Linguagem')
    else:
        CDU_lista.append('Geografia. Biografia. História')

emprestimos_biblioteca['CDU_geral'] = CDU_lista

emprestimos_biblioteca['CDU_geral']

0          Geografia. Biografia. História
1          Geografia. Biografia. História
2          Geografia. Biografia. História
3          Geografia. Biografia. História
8          Geografia. Biografia. História
                        ...
2804250    Geografia. Biografia. História
2804251    Geografia. Biografia. História
2804252    Geografia. Biografia. História
2804253                       Belas artes
2804254    Geografia. Biografia. História
Name: CDU_geral, Length: 2804218, dtype: str

In [17]:
emprestimos_biblioteca.head()

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema,CDU_geral
0,709684.0,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,Geografia. Biografia. História
1,709685.0,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,Geografia. Biografia. História
2,709686.0,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,Geografia. Biografia. História
3,709687.0,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,Geografia. Biografia. História
8,709688.0,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,Geografia. Biografia. História

### Excluir a coluna "registro_sistema"

In [18]:
emprestimos_biblioteca.drop(columns=['registro_sistema'], inplace=True)

### Alterar o tipo de dado da matrícula

In [19]:
emprestimos_biblioteca['matricula_ou_siape'] = emprestimos_biblioteca['matricula_ou_siape'].astype(str)